declare enum PLAYER {
  ONE = 0,
  TWO = 1
}

declare enum LOCATION {
  'DECK',
  'HAND',
  'TRASH',
  'EGG',
  'SECURITY',
  'BREEDINGZONE',
  'BATTLEZONE',
  'EXCAVATED',
  'INMATERIAL',
  'ONFIELD'
}

declare enum LEVEL {
  BABY = 2,
  ROOKIE = 3,
  CHAMPION = 4,
  ULTIMATE = 5,
  MEGA = 6,
  BEYOND = 7,
  'Armor'
}

declare enum COLOR {
  RED = 0,
  BLUE = 1,
  YELLOW = 2,
  GREEN = 3,
  PURPLE = 4,
  BLACK = 5,
  WHITE = 6,
  COLORLESS = 7
}

declare enum ATTRIBUTE {
  Vaccine = 0,
  Data = 1,
  Virus = 2
}

declare enum TYPE {
  'AA Defense Agent',
  'Ability Synthesis Agent',
  'Abnormal',
  'Alien',
  'Alien Humanoid',
  'Amphibian',
  'Ancient',
  'Ancient Animal',
  'Ancient Bird',
  'Ancient Birdkin',
  'Ancient Dragon',
  'Ancient Dragonkin',
  'Ancient Fish',
  'Ancient Holy Warrior',
  'Ancient Insectoid',
  'Ancient Mineral',
  'Ancient Mythical Beast',
  'Ancient Plant',
  'Android',
  'Angel',
  'Animal',
  'Ankylosaur',
  'Aquabeast',
  'Aquatic',
  'Archangel',
  'Armor',
  'Authority',
  'Avian',
  'Baby Dragon',
  'Base Defense Agent',
  'Beast',
  'Beast Dragon',
  'Beast Knight',
  'Beastkin',
  'Bird',
  'Bird Dragon',
  'Birdkin',
  'Blue Flare',
  'Bulb',
  'Carnivorous Plant',
  'Ceratopsian',
  'Cherub',
  'Chick',
  'Commander Agent',
  'Composite',
  'Composition',
  'CRT',
  'Crustacean',
  'Cyborg',
  'Dark Animal',
  'Dark Dragon',
  'Dark Knight',
  'Data',
  'Demon',
  'Demon Lord',
  'Dinosaur',
  'Dragon',
  'Dragon Warrior',
  'Dragonkin',
  'Earth Dragon',
  'Enhancement',
  'Espionage Agent',
  'Evil',
  'Evil Dragon',
  'Fairy',
  'Fallen Angel',
  'Fire',
  'Fire Dragon',
  'Flame',
  'Food',
  'Four Great Dragons',
  'General',
  'Ghost',
  'Giant Bird',
  'Grappling Agent',
  'Ground Combat Agent',
  'Holy Beast',
  'Holy Bird',
  'Holy Dragon',
  'Holy Sword',
  'Holy Warrior',
  'Ice-Snow',
  'Icy',
  'Insectoid',
  'Intel Acquisition Agent',
  'Invader',
  'Larva',
  'LCD',
  'Legend-Arms',
  'Lesser',
  'Light Dragon',
  'Machine',
  'Machine Dragon',
  'Magic Knight',
  'Magic Warrior',
  'Major',
  'Mammal',
  'Marine Man',
  'Mine',
  'Mineral',
  'Mini Angel',
  'Mini Bird',
  'Mini Dragon',
  'Minor',
  'Mollusk',
  'Monk',
  'Mothership Agent',
  'Musical Instrument',
  'Mutant',
  'Mysterious Beast',
  'Mysterious Bird',
  'Mythical',
  'Mythical Animal',
  'Mythical Beast',
  'Mythical Dragon',
  'NO DATA',
  'Parasite',
  'Perfect',
  'Pixie',
  'Plesiosaur',
  'Puppet',
  'Rare Animal',
  'Reconnaissance Agent',
  'Reptile',
  'Reptile Man',
  'Rock',
  'Rock Dragon',
  'Royal Knight',
  'Sea Animal',
  'Sea Beast',
  'Seraph',
  'Shaman',
  'Skeleton',
  'Sky Dragon',
  'Super Major',
  'Throne',
  'Twilight',
  'Unanalyzable',
  'Undead',
  'Unidentified',
  'Unique',
  'Unknown',
  'Vegetation',
  'Virtue',
  'Warrior',
  'Weapon',
  'Wizard',
  'X Antibody',
  'Xros Heart'
}

declare type DigivolutionCost = {
  color: COLOR;
  cost: number;
  level?: LEVEL;
  digimon: string[];
};
